FROM php:7.4-fpm

RUN docker-php-ext-install pdo_mysql

RUN apt-get update && \
apt-get install -y \
zlib1g-dev
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --filename=composer \
    && php -r "unlink('composer-setup.php');" \
    && mv composer /usr/local/bin/composer

WORKDIR /usr/src/app

RUN PATH=$PATH:/usr/src/apps/vendor/bin:bin
